name: nhs-rtt-msc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2
  - numpy=1.26
  - pyarrow=16.1
  - beautifulsoup4=4.12
  - lxml=5.2
  - tqdm=4.66
  - matplotlib=3.9.2
  - scikit-learn=1.5
  - pytorch=2.3
  - shap=0.46
  - pulp=2.8
  - plotly=5.22
  - kaleido=0.2
  - streamlit=1.36
  - pillow=10.4
  - nbformat=5.10
  - pytest=8.2
  - pip
